### ISSUE TITLE
Contract Pack "tip" key is adding loading tip messages to the message roll.

### ISSUE THREAD

**Issue by Poodmund** [linuxgurugamer/KSPLoadingScreenManager#1]
It seems LSM is pulling tips from Contract Pack config nodes into the Loading Screen tip messages, i.e. both:

```
UrlConfig
{
    name = Strategia
    type = CONTRACT_GROUP
    parentUrl = Strategia/Contracts/Strategia
    url = Strategia/Contracts/Strategia/Strategia
    CONTRACT_GROUP
    {
        name = Strategia
        displayName = Strategia
        minVersion = 1.17.0
        agent = Strategia
        tip = Strategizing...
    }
}
```

... and 

```
UrlConfig
{
    name = ExplorationPlus
    type = CONTRACT_GROUP
    parentUrl = ContractPacks/ExplorationPlus/ExplorationPlus
    url = ContractPacks/ExplorationPlus/ExplorationPlus/ExplorationPlus
    CONTRACT_GROUP
    {
        name = ExplorationPlus
        displayName = Exploration Plus
        agent = Exploration
        minVersion = 1.21.0
        disabledContractType = ExplorationContract
        tip = Being "Explorery"
        DATA
        {
            type = int
            returnHome = Random(1,3)
        }
    }
}
```

Insert the loading screen tips, 'Strategizing...' and 'Being "Explorery"' in the roll of loading screen messages.

**Comment by Galileo88** [comment]
Ah, you found it!!! Explains why I don't see it. I don't use that contract pack

**Comment by linuxgurugamer** [comment]
The LSM mod doesn't read anything, is it possible that those tips are somehow being included by stock?

**Comment by Poodmund** [comment]
No they are absolutely from those 2 contract packs and the Being "Explorery" I'm 99% sure is not from the vanilla game as it does not have the ellipses as all the other vanilla loading tips do.

Could it be that LSM is reading from the MM cache and using those lines as tips?

**Comment by linuxgurugamer** [comment]
No, LSM gets tips from stock.
I'll go over it again, but I'm still wondering if the game is loaded the tips incorrectly.

**Comment by linuxgurugamer** [comment]
Been looking into this, can you see if it's still happening?  If it is, please check to see what the tipsFile is pointing to, and look into that file to see if these tips are in there

Thanks

**Comment by linuxgurugamer** [comment]
Reopen if it's still happening
