### ISSUE TITLE
Broken Links on GitHub Main Page

### ISSUE THREAD

**Issue by JustaSimpleUser** [linuxgurugamer/KSPLoadingScreenManager#6]
The links for the 32 and 64-bit versions on the main GitHub page under _Installation_ are broken.

**Comment by linuxgurugamer** [comment]
That was from the original mod.  To get any of the current releases, go to:

https://github.com/linuxgurugamer/KSPLoadingScreenManager/releases

This mod has been deprecated and is not supported any more, due to the inclusion of the functionality in stock
